[package]
name = "exyleio-api"
version = "0.1.0"
edition = "2021"

[dependencies]
r2d2 = "0.8.10"
r2d2_redis = "0.14.0"
redis = "0.22.1"
rocket = "0.5.0-rc.2"
rocket_db_pools = { version = "0.1.0-rc.2", features = ["deadpool_redis"] }
