version: "3"
services:
  redis:
    image: redis:7-alpine
    container_name: exyleio-redis
    restart: unless-stopped
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf

  api:
    depends_on:
      - redis
    container_name: exyleio-api
    restart: unless-stopped
    ports:
      - 8000:8000
    build: .
    volumes:
      - .:/app
