version: "3"
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf

  api:
    depends_on:
      - redis
    restart: unless-stopped
    ports:
      - 80:8000
    build: .
    volumes:
      - .:/app

  web:
    depends_on:
      - api
    image: developomp/exyleio-web:latest
    restart: unless-stopped
    ports:
      - 5173:80
