version: "3"
services:
  db:
    image: "redis:7-alpine"
    restart: always
    network_mode: "host"

  server:
    depends_on:
      - db
    restart: always
    network_mode: "host"
    build: .
    volumes:
      - .:/app
