version: "3"
services:
  redis:
    image: "redis:7-alpine"
    restart: unless-stopped
    command: redis-server --bind 0.0.0.0 --port 6379
    network_mode: "host"

  pocketbase:
    image: spectado/pocketbase:latest
    restart: unless-stopped
    command: pocketbase serve --http=0.0.0.0:8090
    network_mode: "host"
    volumes:
      - ./pb_data:/pb_data

  api:
    depends_on:
      - redis
      - pocketbase
    restart: unless-stopped
    network_mode: "host"
    build: .
    volumes:
      - .:/app
