version: "3"
services:
  redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis-stack.conf:/redis-stack.conf
      - ./redis_stack_data/:/data

  api:
    depends_on:
      - redis
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 80:8000
    build: .
    volumes:
      - .:/app

  web:
    depends_on:
      - api
    image: developomp/exyleio-web:latest
    restart: unless-stopped
    ports:
      - 5173:80
